language: cpp
compiler:
  - gcc
  - clang

before_install:
  - yes | sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi

script: $CXX --version && cmake . -G 'Unix Makefiles' && make && ./TemporaryProject