language: cpp
compiler:
  - gcc
  - clang

before_install:
  - yes | sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON ..
  - make
  - ./test/TemporaryProject_Test
