environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build: off

test_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DBUILD_TESTS=ON ..
  - cmd: cmake --build .
  - cmd: dir
  - cmd: cd Debug
  - cmd: dir
  - cmd: "TemporaryProject_Test.exe"
